### ISSUE TITLE
use npm rather than npx for prettier

### ISSUE THREAD

**Issue by kwypchlo** [SkynetLabs/.github#9]
> If you mean the composite action in this repo, that is for `yarn` projects, and also requires more configuration whereas I prefer to have a single action that has all the basic checks.
> 
> For npm projects, using `npx` is the recommended way:
> 
> https://prettier.io/docs/en/install.html
> 
> `npx` will use the locally-installed version of prettier if found, according to these docs.

There's also a warning that you should not run npx if you don't have it added as a package. I suggest using `npm run prettier --check .` to ensure we're running the locally installed version and if it's not installed it should fail until we do.

> Note: If you forget to install Prettier first, npx will temporarily download the latest version. That’s not a good idea when using Prettier, because we change how code is formatted in each release! It’s important to have a locked down version of Prettier in your package.json. And it’s faster, too.

_Originally posted by @kwypchlo in https://github.com/SkynetLabs/.github/pull/8#discussion_r850271222_

**Comment by m-cat** [comment]
> I suggest using `npm run prettier --check .` to ensure we're running the locally installed version and if it's not installed it should fail until we do.

@kwypchlo This will try to run a `prettier` script in the `"scripts"` section and fail if it's not there. `npm run` would require the consuming repos to have a script called `prettier`.

I've confirmed that `npx` will run the local version of prettier if one is specified in `devDependencies`. Try changing the version in `package.json` and running:

```
npx prettier --version
```

> There's also a warning that you should not run npx if you don't have it added as a package.

We can run it with the `--no-install` option to ensure it doesn't try to install its own prettier. I think I would prefer that as opposed to having a `"prettier": "prettier"` script which seems useless to me. Even without `--no-install`, *I think* you still need to provide a y/n answer for it to install anything, so in CI it would just time out.

Not sure what the best practice is, but prettier docs recommend `npx`.

**Comment by kwypchlo** [comment]
--no-install sounds great :)
